### ISSUE TITLE
Build windows binaries

### ISSUE THREAD

**Issue by flavioschuindt** [guidowb/cf-targets-plugin#11]
It would be great to have windows binaries available. I was not able to install cf-targets-plugin using `cf install-plugin` command. I had first to generate windows binaries using go and then use `cf install-plugin` pointing to the executable file. It would be really nice if we had the windows binaries available to install directly.

**Comment by guidowb** [comment]
Windows binaries are available both in this repo and on https://plugins.cloudfoundry.org
