### ISSUE TITLE
go build is failing

### ISSUE THREAD

**Issue by punalpatel** [guidowb/cf-targets-plugin#13]
$ go build
cf_targets.go:14:2: cannot find package "github.com/cloudfoundry/cli/cf/configuration/config_helpers" in any of:
	/usr/local/go/src/github.com/cloudfoundry/cli/cf/configuration/config_helpers (from $GOROOT)
	/Users/ppatel/go/bin/src/github.com/cloudfoundry/cli/cf/configuration/config_helpers (from $GOPATH)
cf_targets.go:15:2: cannot find package "github.com/cloudfoundry/cli/cf/configuration/core_config" in any of:
	/usr/local/go/src/github.com/cloudfoundry/cli/cf/configuration/core_config (from $GOROOT)
	/Users/ppatel/go/bin/src/github.com/cloudfoundry/cli/cf/configuration/core_config (from $GOPATH)

**Comment by loafoe** [comment]
@punalpatel I opened a PR #12 that fixes the build, at least for me.

**Comment by guidowb** [comment]
PR was merged (woefully late, I know). If you still see build problems please feel free to open a new issue.
