### ISSUE TITLE
Fix case in install instructions

### ISSUE THREAD

**Issue by jmcarp** [guidowb/cf-targets-plugin#17]
The install instructions currently fail with `Plugin targets not found in repository CF-Community.`. Looks like this plugin is registered as `Targets`, and the `install-plugin` command is case-sensitive. Installing with `Targets` instead of `targets` works.

To fix, we can change the instructions to use `Targets`, change the name of the plugin to `targets` in the plugin registry, or update the cli to do case-insensitive matching. Any preferences?

**Comment by guidowb** [comment]
Fixed by 87f2403deeeed78313fb4904bf20503131321ebd
